### ISSUE TITLE
why it's not working ?

### ISSUE THREAD

**Issue by NizarETH** [FrancisToth/buck_with_android_projects#2]
I clone the project, I past the command in terminal, it gives me that message :
This does not appear to be the root of a Buck project. Please 'cd'
to the root of your project before running buck. If this really is
the root of your project, run
'touch .buckconfig'

I create tje .buckconfig file and when I run the giving command it shows me that error :

BUILD FAILED: Parse error for build file /Users/euphor/test/buck_with_android_projects/app/BUCK: End of input at line 1 column 1

**Comment by FrancisToth** [comment]
This project is outdated. I've made some quick changes to make it work, tell me if you need support.

**Comment by NizarETH** [comment]
Thank's a lot but I used Gradle, I'll come back soon to Buck.

Have a nice day, thank you.
